In [5]:
import sys
print(sys.executable)

c:\Users\USER\AppData\Local\Programs\Python\Python311\python.exe

In [6]:
import sys
!{sys.executable} -m pip install ucimlrepo

Requirement already satisfied: ucimlrepo in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ucimlrepo) (3.0.6)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from ucimlrepo) (2026.7.22)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python311\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2026.4)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
from ucimlrepo import fetch_ucirepo

print("ucimlrepo imported successfully!")

ucimlrepo imported successfully!

In [8]:
from ucimlrepo import fetch_ucirepo

# Fetch UCI Student Performance dataset
student_performance = fetch_ucirepo(id=320)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [9]:
X = student_performance.data.features
y = student_performance.data.targets

print("Features shape:", X.shape)
print("Target shape:", y.shape)

display(X.head())
display(y.head())

Features shape: (649, 30)
Target shape: (649, 3)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,yes,no,no,4,3,4,1,1,3,4
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,yes,no,5,3,3,1,1,3,2
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,yes,no,4,3,2,2,3,3,6
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,yes,3,2,2,1,1,5,0
4,GP,F,16,U,GT3,T,3,3,other,other,...,yes,no,no,4,3,2,1,2,5,0

   G1  G2  G3
0   0  11  11
1   9  11  11
2  12  13  12
3  14  14  14
4  11  13  13

In [10]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    str
 1   sex         649 non-null    str
 2   age         649 non-null    int64
 3   address     649 non-null    str
 4   famsize     649 non-null    str
 5   Pstatus     649 non-null    str
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    str
 9   Fjob        649 non-null    str
 10  reason      649 non-null    str
 11  guardian    649 non-null    str
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    str
 16  famsup      649 non-null    str
 17  paid        649 non-null    str
 18  activities  649 non-null    str
 19  nursery     649 non-null    str
 20  higher      649 non-null    str
 21  internet    649 non-null    str
 22  romantic    649 non-null    str
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
dtypes: int64(13), str(17)
memory usage: 152.2 KB

In [11]:
print("Target column:")
display(y.head(10))

print("\nTarget information:")
y.info()

print("\nTarget statistics:")
display(y.describe())

Target column:

   G1  G2  G3
0   0  11  11
1   9  11  11
2  12  13  12
3  14  14  14
4  11  13  13
5  12  12  13
6  13  12  13
7  10  13  13
8  15  16  17
9  12  12  13

Target information:
<class 'pandas.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   G1      649 non-null    int64
 1   G2      649 non-null    int64
 2   G3      649 non-null    int64
dtypes: int64(3)
memory usage: 15.3 KB

Target statistics:

               G1          G2          G3
count  649.000000  649.000000  649.000000
mean    11.399076   11.570108   11.906009
std      2.745265    2.913639    3.230656
min      0.000000    0.000000    0.000000
25%     10.000000   10.000000   10.000000
50%     11.000000   11.000000   12.000000
75%     13.000000   13.000000   14.000000
max     19.000000   19.000000   19.000000

In [12]:
print(y["G3"].value_counts().sort_index())

G3
0      15
1       1
5       1
6       3
7      10
8      35
9      35
10     97
11    104
12     72
13     82
14     63
15     49
16     36
17     29
18     15
19      2
Name: count, dtype: int64

In [13]:
risk_target = y["G3"].apply(
    lambda grade: "At-Risk" if grade < 10 else "Not-At-Risk"
)

print(risk_target.value_counts())

G3
Not-At-Risk    549
At-Risk        100
Name: count, dtype: int64

In [14]:
print("Class counts:")
print(risk_target.value_counts())

print("\nClass percentages:")
print(risk_target.value_counts(normalize=True) * 100)

Class counts:
G3
Not-At-Risk    549
At-Risk        100
Name: count, dtype: int64

Class percentages:
G3
Not-At-Risk    84.59168
At-Risk        15.40832
Name: proportion, dtype: float64

In [15]:
print(X.columns.tolist())

['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences']

In [16]:
print(y.columns.tolist())

['G1', 'G2', 'G3']

In [17]:
X_early = X.copy()
y_risk = risk_target

print("X shape:", X_early.shape)
print("y shape:", y_risk.shape)

X shape: (649, 30)
y shape: (649,)

In [18]:
import sys
!{sys.executable} -m pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)

[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_early,
    y_risk,
    test_size=0.20,
    random_state=42,
    stratify=y_risk
)

print("Training students:", len(X_train))
print("Testing students:", len(X_test))

print("\nTraining classes:")
print(y_train.value_counts())

print("\nTesting classes:")
print(y_test.value_counts())

Training students: 519
Testing students: 130

Training classes:
G3
Not-At-Risk    439
At-Risk         80
Name: count, dtype: int64

Testing classes:
G3
Not-At-Risk    110
At-Risk         20
Name: count, dtype: int64

In [20]:
print("X exists:", "X" in globals())
print("risk_target exists:", "risk_target" in globals())
print("X_early exists:", "X_early" in globals())
print("X_train exists:", "X_train" in globals())

X exists: True
risk_target exists: True
X_early exists: True
X_train exists: True

In [21]:
categorical_cols = X_train.select_dtypes(include="object").columns.tolist()
numerical_cols = X_train.select_dtypes(include="number").columns.tolist()

print("Categorical features:")
print(categorical_cols)

print("\nNumerical features:")
print(numerical_cols)

print("\nNumber of categorical features:", len(categorical_cols))
print("Number of numerical features:", len(numerical_cols))

Categorical features:
['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']

Numerical features:
['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences']

Number of categorical features: 17
Number of numerical features: 13

C:\Users\USER\AppData\Local\Temp\ipykernel_20160\2554123774.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X_train.select_dtypes(include="object").columns.tolist()

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
        ("num", StandardScaler(), numerical_cols)
    ]
)

print("Preprocessor created successfully!")

Preprocessor created successfully!

In [23]:
from sklearn.dummy import DummyClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

baseline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", DummyClassifier(strategy="most_frequent"))
])

baseline.fit(X_train, y_train)

baseline_predictions = baseline.predict(X_test)

print("Accuracy:",
      accuracy_score(y_test, baseline_predictions))

print("Recall:",
      recall_score(
          y_test,
          baseline_predictions,
          pos_label="At-Risk",
          zero_division=0
      ))

print("Precision:",
      precision_score(
          y_test,
          baseline_predictions,
          pos_label="At-Risk",
          zero_division=0
      ))

print("F1:",
      f1_score(
          y_test,
          baseline_predictions,
          pos_label="At-Risk",
          zero_division=0
      ))

Accuracy: 0.8461538461538461
Recall: 0.0
Precision: 0.0
F1: 0.0